Repository AutarkLabs/open-enterprise, pull requests merged in 2019-12, with the labels that each got.

#1754 Rewards/MyRewards: Double Check Icon
  apps/rewards/app/assets/double-check.svg
  apps/rewards/app/utils/helpers.js
Labels: mainnet

#1753 Rewards: changed "next payout" to always be in the future
  apps/rewards/app/components/Content/Overview.js
Labels: mainnet

#1755 Rewards/NewReward: rename "reference asset" to "reference token"
  apps/rewards/app/components/Panel/NewReward/NewReward.js
Labels: mainnet

#1752 Rewards/NewReward: display warnings on valid form only
  apps/rewards/app/components/Panel/NewReward/NewReward.js
Labels: app: rewards

#1762 Projects/ReviewApplication: hypertext links
  apps/projects/app/components/Panel/ReviewApplication/ReviewApplication.js
  apps/projects/app/components/Panel/ReviewWork/ReviewWork.js
  shared/ui/components/misc/DetailHyperText.js
  shared/ui/components/misc/Markdown.js
  shared/ui/components/misc/index.js
Labels: app: projects

#1722 AragonUI 1.0.0 upgrade
  apps/address-book/package.json
  apps/allocations/app/components/Panel/NewBudget.js
  apps/allocations/package.json
  apps/dot-voting/package.json
  apps/projects/package.json
  apps/rewards/package.json
  shared/ui/package.json
Labels: mainnet

#1782 Allocations/routing: wait, don't redirect
  apps/allocations/app/components/App/App.js
  apps/allocations/app/components/App/BudgetDetail.js
  apps/allocations/app/components/Card/Budget.js
  apps/allocations/app/hooks/usePathHelpers.js
Labels: mainnet

#1794 Allocations/NewAllocation: fix when no budget id
  apps/allocations/app/components/Panel/NewAllocation.js
Labels: app: allocations, mainnet

#1679 Projects deep links implementation
  apps/projects/app/App.js
  apps/projects/app/api-react.js
  apps/projects/app/components/Card/Issue.js
  apps/projects/app/components/Card/Project.js
  apps/projects/app/components/Content/Issues.js
  apps/projects/app/components/Content/Overview.js
  apps/projects/app/hooks/usePathSegments.js
Labels: mainnet

#1740 Rewards: Deep linking
  apps/address-book/package.json
  apps/rewards/app/app-logic.js
  apps/rewards/app/components/App/App.js
Labels: mainnet

#1787 Allocation: add support for tokens with different decimal amounts
  apps/allocations/app/app-state-reducer.js
  apps/allocations/app/components/App/AllocationsHistory.js
  apps/allocations/app/components/App/Payouts.js
  apps/allocations/app/components/Card/Budget.js
  apps/allocations/app/components/Panel/NewAllocation.js
  apps/allocations/app/utils/helpers.js
  shared/ui/constants.js
  shared/ui/helpers.js
Labels: app: allocations, mainnet
